export function forgeUi(): Response {
  return new Response(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>Forge</title>
<style>
:root{color-scheme:dark;--bg:#0d1117;--panel:#161b22;--line:#30363d;--muted:#8b949e;--text:#e6edf3;--accent:#2f81f7;--green:#3fb950}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.5 ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}a{color:#58a6ff;text-decoration:none}button,input,textarea,select{font:inherit}.top{height:58px;border-bottom:1px solid var(--line);display:flex;align-items:center;padding:0 24px;gap:18px;background:#010409}.brand{font-weight:700;color:white;font-size:17px}.pill{border:1px solid var(--line);border-radius:6px;background:var(--panel);color:var(--text);padding:5px 10px}.wrap{max-width:1180px;margin:0 auto;padding:28px 22px}.row{display:flex;gap:16px;align-items:center}.between{justify-content:space-between}.card{border:1px solid var(--line);background:var(--panel);border-radius:8px}.repo{padding:16px 18px;border-bottom:1px solid var(--line)}.repo:last-child{border-bottom:0}.repo h3{margin:0 0 5px}.muted{color:var(--muted)}.title{font-size:22px;font-weight:600;margin:0}.btn{border:1px solid rgba(240,246,252,.1);border-radius:6px;background:#238636;color:#fff;padding:7px 12px;font-weight:600;cursor:pointer}.btn.secondary{background:#21262d}.tabs{display:flex;border-bottom:1px solid var(--line);gap:8px;margin-top:20px}.tab{background:none;border:0;color:var(--muted);padding:10px 12px;cursor:pointer;border-bottom:2px solid transparent}.tab.active{color:var(--text);border-bottom-color:#f78166}.browser{margin-top:18px;overflow:hidden}.crumb{padding:10px 14px;border-bottom:1px solid var(--line)}.entry{display:grid;grid-template-columns:32px 1fr 140px;padding:9px 14px;border-bottom:1px solid #21262d;cursor:pointer}.entry:last-child{border-bottom:0}.entry:hover{background:#1c2128}.code{margin:0;white-space:pre;overflow:auto;padding:18px;background:#0d1117;max-height:70vh;font:12px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace}.modal{position:fixed;inset:0;background:#0009;display:none;place-items:center;padding:20px}.modal.open{display:grid}.dialog{width:min(560px,100%);padding:20px}.field{display:grid;gap:6px;margin:12px 0}.field input,.field textarea,.field select{width:100%;background:#0d1117;color:var(--text);border:1px solid var(--line);border-radius:6px;padding:9px}.secret{background:#1f2428;border:1px solid #9e6a03;padding:12px;border-radius:6px;word-break:break-all}.empty{padding:32px;text-align:center;color:var(--muted)}.error{padding:12px;border:1px solid #f8514966;background:#f8514914;border-radius:6px;color:#ff7b72}.commit{padding:10px 14px;border-bottom:1px solid var(--line)}@media(max-width:700px){.wrap{padding:18px 12px}.entry{grid-template-columns:25px 1fr}.entry span:last-child{display:none}}
</style>
</head>
<body>
<header class="top"><a class="brand" href="/">◆ Forge</a><span class="muted">Cloudflare Artifacts</span><span style="flex:1"></span><a class="pill" href="/mcp">MCP</a><a class="pill" href="/api/capabilities">API</a></header>
<main id="app" class="wrap"><div class="muted">Loading…</div></main>
<div id="modal" class="modal"><div class="dialog card" id="dialog"></div></div>
<script>
const app=document.querySelector('#app'),modal=document.querySelector('#modal'),dialog=document.querySelector('#dialog');
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
async function api(name,input={}){const r=await fetch('/api/execute',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,input})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');return j.result}
function openModal(html){dialog.innerHTML=html;modal.classList.add('open')} modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')}
function error(e){app.innerHTML='<div class="error">'+esc(e.message||e)+'</div>'}
async function dashboard(){
  app.innerHTML='<div class="row between"><div><h1 class="title">Repositories</h1><div class="muted">Git repositories stored in Cloudflare Artifacts.</div></div><button id="new" class="btn">New repository</button></div><div id="repos" class="card" style="margin-top:20px"><div class="empty">Loading…</div></div>';
  document.querySelector('#new').onclick=()=>openModal('<h2 style="margin-top:0">Create repository</h2><form id="create"><label class="field">Owner<input name="owner" required></label><label class="field">Name<input name="repo" required></label><label class="field">Description<textarea name="description"></textarea></label><label class="field">Visibility<select name="visibility"><option>private</option><option>public</option></select></label><div class="row" style="justify-content:flex-end"><button type="button" class="btn secondary" onclick="modal.classList.remove(\'open\')">Cancel</button><button class="btn">Create</button></div></form><div id="created"></div>');
  document.addEventListener('submit',async e=>{if(e.target.id!=='create')return;e.preventDefault();const f=new FormData(e.target);try{const out=await api('repo.create',{owner:f.get('owner'),repo:f.get('repo'),description:f.get('description')||undefined,visibility:f.get('visibility')});document.querySelector('#created').innerHTML='<p>Repository created.</p><div class="secret"><b>Initial Git token — shown once</b><br>'+esc(typeof out.initialToken==='string'?out.initialToken:JSON.stringify(out.initialToken))+'</div><p><a href="/r/'+encodeURIComponent(f.get('owner'))+'/'+encodeURIComponent(f.get('repo'))+'">Open repository →</a></p>'}catch(err){document.querySelector('#created').innerHTML='<div class="error">'+esc(err.message)+'</div>'}});
  const repos=await api('repo.list');document.querySelector('#repos').innerHTML=repos.length?repos.map(r=>'<div class="repo"><h3><a href="/r/'+encodeURIComponent(r.owner)+'/'+encodeURIComponent(r.name)+'">'+esc(r.owner)+' / '+esc(r.name)+'</a> <span class="pill">'+esc(r.visibility)+'</span></h3><div class="muted">'+esc(r.description||'No description')+' · '+esc(r.default_branch)+'</div></div>').join(''):'<div class="empty">No repositories yet.</div>';
}
async function repository(owner,repo){
  app.innerHTML='<div class="row between"><div><h1 class="title"><a href="/">'+esc(owner)+'</a> / '+esc(repo)+'</h1><div id="desc" class="muted"></div></div><button id="clone" class="btn secondary">Clone token</button></div><div class="tabs"><button class="tab active" data-tab="code">Code</button><button class="tab" data-tab="commits">Commits</button><button class="tab" data-tab="issues">Issues</button><button class="tab" data-tab="pulls">Pull requests</button></div><section id="view"></section>';
  const meta=await api('repo.get',{owner,repo});document.querySelector('#desc').textContent=meta.description||'';
  document.querySelector('#clone').onclick=async()=>{try{const t=await api('repo.token.create',{owner,repo,scope:'read',ttl:3600});openModal('<h2 style="margin-top:0">Clone token</h2><div class="secret">'+esc(t.plaintext)+'</div><p class="muted">Expires '+esc(t.expiresAt||'soon')+'. Use as the Git HTTP password with username x.</p>')}catch(e){openModal('<div class="error">'+esc(e.message)+'</div>')}};
  document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');loadTab(t.dataset.tab,meta)});loadTab('code',meta);
  async function loadTab(tab,meta){const view=document.querySelector('#view');view.innerHTML='<div class="empty">Loading…</div>';try{
    if(tab==='commits'){const logs=await api('git.log',{owner,repo,ref:meta.default_branch,limit:50});const arr=Array.isArray(logs)?logs:(logs.commits||[]);view.innerHTML='<div class="card browser">'+(arr.length?arr.map(c=>'<div class="commit"><b>'+esc((c.message||'').split('\\n')[0])+'</b><div class="muted">'+esc((c.hash||'').slice(0,10))+' · '+esc(c.author?.name||'')+'</div></div>').join(''):'<div class="empty">No commits.</div>')+'</div>';return}
    if(tab==='issues'){const rows=await api('issue.list',{owner,repo});view.innerHTML='<div class="card browser">'+(rows.length?rows.map(i=>'<div class="repo"><b>#'+i.number+' '+esc(i.title)+'</b><div class="muted">'+esc(i.state)+' · '+esc(i.author)+'</div></div>').join(''):'<div class="empty">No issues.</div>')+'</div>';return}
    if(tab==='pulls'){const rows=await api('pull.list',{owner,repo});view.innerHTML='<div class="card browser">'+(rows.length?rows.map(p=>'<div class="repo"><b>#'+p.number+' '+esc(p.title)+'</b><div class="muted">'+esc(p.state)+' · '+esc(p.head_ref)+' → '+esc(p.base_ref)+'</div></div>').join(''):'<div class="empty">No pull requests.</div>')+'</div>';return}
    const logs=await api('git.log',{owner,repo,ref:meta.default_branch,limit:1});const arr=Array.isArray(logs)?logs:(logs.commits||[]);if(!arr.length){view.innerHTML='<div class="card browser empty">Empty repository. Push an initial commit to '+esc(meta.default_branch)+'.</div>';return}await showTree(arr[0].treeHash,'',view);
  }catch(e){view.innerHTML='<div class="error" style="margin-top:18px">'+esc(e.message)+'</div>'}}
  async function showTree(hash,path,view){const tree=await api('git.tree',{owner,repo,hash});const entries=Array.isArray(tree)?tree:(tree.entries||[]);view.innerHTML='<div class="card browser"><div class="crumb">'+(path?'<a href="#" id="root">'+esc(repo)+'</a> / '+esc(path):esc(repo))+'</div><div id="entries">'+entries.map(x=>'<div class="entry" data-name="'+esc(x.name)+'" data-hash="'+esc(x.hash)+'" data-type="'+esc(x.type)+'"><span>'+(x.type==='tree'?'▣':'·')+'</span><span>'+esc(x.name)+'</span><span class="muted">'+esc(x.type)+'</span></div>').join('')+'</div></div>';view.querySelectorAll('.entry').forEach(el=>el.onclick=async()=>{const next=path?path+'/'+el.dataset.name:el.dataset.name;if(el.dataset.type==='tree')return showTree(el.dataset.hash,next,view);try{const f=await api('fs.read',{owner,repo,ref:meta.default_branch,path:next});view.innerHTML='<div class="card browser"><div class="crumb"><a href="javascript:location.reload()">'+esc(repo)+'</a> / '+esc(next)+'</div><pre class="code">'+esc(f.text)+'</pre></div>'}catch(e){view.innerHTML='<div class="error">'+esc(e.message)+'</div>'}})}
}
(async()=>{try{const m=location.pathname.match(/^\\/r\\/([^/]+)\\/([^/]+)\\/?$/);if(m)await repository(decodeURIComponent(m[1]),decodeURIComponent(m[2]));else await dashboard()}catch(e){error(e)}})();
</script>
</body></html>`, { headers: { 'content-type': 'text/html; charset=utf-8' } });
}
