import { useState, useTransition } from "react";
import { useParams } from "react-router-dom";
import { api, type Commit, type Resolved } from "../api";
import { useRepo } from "./RepoLayout";
import { useData } from "../data";
import { Box } from "../components/Layout";
import { RefBar } from "../components/RefBar";
import { CommitRow } from "../components/CommitRow";
export function CommitsPage() { const { full } = useRepo(); const rest = useParams()["*"] ?? ""; const resolved = useData(`resolve:${full}:${rest}`, () => api.resolve(full, rest)); return <CommitList key={`${resolved.sha}:${resolved.path}`} full={full} resolved={resolved} />; }
function CommitList({ full, resolved }: { full: string; resolved: Resolved }) { const [isPending, startTransition] = useTransition(); const first = useData(`commits:${full}:${resolved.sha}:${resolved.path}:0`, () => api.commits(full, resolved.sha, resolved.path, 0), Infinity); const [extra, setExtra] = useState<{ commits: Commit[]; more: boolean }>({ commits: [], more: first.more }); const commits = [...first.commits, ...extra.commits]; const groups: { day: string; commits: Commit[] }[] = []; for (const commit of commits) { const day = new Date(commit.commit_date).toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" }); const group = groups.at(-1); if (group?.day === day) group.commits.push(commit); else groups.push({ day, commits: [commit] }); } const loadMore = () => startTransition(async () => { const page = await api.commits(full, resolved.sha, resolved.path, commits.length); startTransition(() => setExtra((state) => ({ commits: [...state.commits, ...page.commits], more: page.more }))); }); return <><RefBar refname={resolved.ref} refKind={resolved.kind} path={resolved.path} page="commits" />{groups.map((group) => <div key={group.day} className="commit-group"><div className="commit-day muted">Commits on {group.day}</div><Box>{group.commits.map((commit) => <CommitRow key={commit.sha} repo={full} commit={commit} />)}</Box></div>)}{commits.length === 0 && <Box><div className="pad muted">No commits.</div></Box>}{extra.more && <div className="center pad"><button className="btn" disabled={isPending} aria-busy={isPending} onClick={loadMore}>{isPending ? "Loading…" : "Older"}</button></div>}</>; }
