import { useEffect, useRef } from "react";

export function Hero() {
  return <section className="hero" aria-labelledby="hero-title"><DagCanvas /><div className="hero-body"><h1 id="hero-title">Forge</h1><p className="hero-lede">A Cloudflare-native Git forge built on Artifacts.</p><p className="hero-text">Git repositories live in Cloudflare Artifacts; working trees run in Sandbox through ArtifactFS, while agents share repository context and memory through the same capability graph.</p><div className="hero-actions"><a href="/api/capabilities" className="btn btn-primary">Explore the API</a><a href="/mcp" className="btn">Open MCP</a></div></div></section>;
}

function DagCanvas() {
  const ref = useRef<HTMLCanvasElement>(null);
  useEffect(() => {
    const canvas = ref.current!; const ctx = canvas.getContext("2d")!; const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches; const styles = getComputedStyle(canvas); const accent = styles.getPropertyValue("--accent").trim() || "#0969da"; const add = styles.getPropertyValue("--add").trim() || "#1a7f37"; const del = styles.getPropertyValue("--del").trim() || "#cf222e"; const palette = [accent, add, "#8250df", del, "#bf8700"];
    type Node = { x: number; y: number; lane: number; r: number; c: string; parents: Node[]; born: number };
    let w = 0; let h = 0; let dpr = 1; const LANES = 7; const nodes: Node[] = []; const speed = 22; let last = performance.now(); let pulseX = -1; let raf = 0;
    const laneY = (lane: number) => ((lane + 1) / (LANES + 1)) * h;
    const findLastNode = (predicate: (node: Node) => boolean) => { for (let index = nodes.length - 1; index >= 0; index -= 1) { const node = nodes[index]!; if (predicate(node)) return node; } return undefined; };
    const spawn = (x: number, now: number) => { const lane = Math.floor(Math.random() * LANES); const node: Node = { x, y: laneY(lane), lane, r: 3 + Math.random() * 2.5, c: palette[lane % palette.length]!, parents: [], born: now }; const same = findLastNode((candidate) => candidate.lane === lane); if (same) node.parents.push(same); if (Math.random() < 0.35) { const other = findLastNode((candidate) => Math.abs(candidate.lane - lane) === 1 && candidate.x < x - 20); if (other) node.parents.push(other); } nodes.push(node); };
    const resize = () => { dpr = Math.min(window.devicePixelRatio || 1, 2); w = canvas.clientWidth; h = canvas.clientHeight; canvas.width = Math.round(w * dpr); canvas.height = Math.round(h * dpr); ctx.setTransform(dpr, 0, 0, dpr, 0, 0); for (const node of nodes) node.y = laneY(node.lane); if (!nodes.length) { const now = performance.now(); for (let x = 20; x < w + 60; x += 28 + Math.random() * 40) spawn(x, now - 5000); } };
    const draw = (now: number) => { const dt = reduce ? 0 : Math.min(0.05, (now - last) / 1000); last = now; for (const node of nodes) node.x -= speed * dt; while (nodes.length && nodes[0]!.x < -40) nodes.shift(); const rightmost = nodes.reduce((max, node) => Math.max(max, node.x), 0); if (rightmost < w + 20) spawn(rightmost + 26 + Math.random() * 44, now); pulseX = reduce ? -1 : ((now / 4000) % 1.6) * (w + 200) - 100; ctx.clearRect(0, 0, w, h); ctx.lineWidth = 1; for (let lane = 0; lane < LANES; lane++) { ctx.strokeStyle = "rgba(120,130,145,0.10)"; ctx.beginPath(); ctx.moveTo(0, laneY(lane)); ctx.lineTo(w, laneY(lane)); ctx.stroke(); } ctx.lineWidth = 1.5; for (const node of nodes) for (const parent of node.parents) { const age = Math.min(1, (now - node.born) / 900); ctx.strokeStyle = hexA(node.c, 0.35 * age); ctx.beginPath(); ctx.moveTo(parent.x, parent.y); const mx = (parent.x + node.x) / 2; ctx.bezierCurveTo(mx, parent.y, mx, node.y, node.x, node.y); ctx.stroke(); } for (const node of nodes) { const age = Math.min(1, (now - node.born) / 600); const near = pulseX >= 0 ? Math.max(0, 1 - Math.abs(node.x - pulseX) / 90) : 0; const radius = node.r * (0.6 + 0.4 * age) + near * 2.5; ctx.fillStyle = hexA(node.c, 0.55 + 0.45 * near); ctx.beginPath(); ctx.arc(node.x, node.y, radius, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = "rgba(255,255,255,0.9)"; ctx.lineWidth = 1.25; ctx.stroke(); } if (pulseX >= 0) { const gradient = ctx.createLinearGradient(pulseX - 120, 0, pulseX + 20, 0); gradient.addColorStop(0, "rgba(9,105,218,0)"); gradient.addColorStop(0.8, "rgba(9,105,218,0.10)"); gradient.addColorStop(1, "rgba(9,105,218,0)"); ctx.fillStyle = gradient; ctx.fillRect(pulseX - 120, 0, 140, h); } if (!reduce) raf = requestAnimationFrame(draw); };
    const onVis = () => { cancelAnimationFrame(raf); if (!document.hidden) { last = performance.now(); raf = requestAnimationFrame(draw); } }; const observer = new ResizeObserver(resize); observer.observe(canvas); resize(); raf = requestAnimationFrame(draw); document.addEventListener("visibilitychange", onVis); return () => { cancelAnimationFrame(raf); observer.disconnect(); document.removeEventListener("visibilitychange", onVis); };
  }, []);
  return <canvas ref={ref} className="hero-canvas" aria-hidden />;
}
function hexA(hex: string, alpha: number): string { const match = /^#?([\da-f]{2})([\da-f]{2})([\da-f]{2})$/i.exec(hex); if (!match) return hex; return `rgba(${parseInt(match[1]!, 16)},${parseInt(match[2]!, 16)},${parseInt(match[3]!, 16)},${alpha.toFixed(3)})`; }
