import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { refListStream, type RefInfo } from "../api";
import { reportError } from "../data";
import { useRepo } from "../pages/RepoLayout";
const PAGE = 50;
export function RefBar({ refname, refKind, path, page }: { refname: string; refKind: "branch" | "tag" | "commit"; path: string; page: "tree" | "blob" | "commits" }) {
  const { full, refs } = useRepo(); const nav = useNavigate(); const [open, setOpen] = useState(false); const [tab, setTab] = useState<"branches" | "tags">(refKind === "tag" ? "tags" : "branches"); const [query, setQuery] = useState("");
  const [list, setList] = useState<{ key: string; refs: RefInfo[]; more: boolean; loading: boolean; error?: string }>({ key: "", refs: [], more: false, loading: false });
  const key = open ? `${full}:${tab}:${query}` : "";
  useEffect(() => { if (!key) return; const controller = new AbortController(); const timer = setTimeout(() => { setList({ key, refs: [], more: false, loading: true }); let batch: RefInfo[] = []; let frame = 0; const paint = () => { frame = 0; if (controller.signal.aborted || batch.length === 0) return; const add = batch; batch = []; setList((state) => state.key === key ? { ...state, refs: [...state.refs, ...add] } : state); }; refListStream(full, tab, { q: query, n: PAGE }, (ref) => { batch.push(ref); if (!frame) frame = requestAnimationFrame(paint); }, controller.signal).then(({ more }) => { cancelAnimationFrame(frame); paint(); if (!controller.signal.aborted) setList((state) => ({ ...state, key, more, loading: false })); }, (error: unknown) => { if (controller.signal.aborted) return; const message = error instanceof Error ? error.message : String(error); reportError(error, `${tab} list`); setList({ key, refs: [], more: false, loading: false, error: message }); }); }, query ? 150 : 0); return () => { controller.abort(); clearTimeout(timer); }; }, [key, full, tab, query]);
  const segments = path ? path.split("/") : []; const crumbKind = page === "commits" ? "commits" : "tree"; const go = (name: string) => { setOpen(false); nav(`/${full}/${page}/${name}${path ? "/" + path : ""}`); }; const shown = list.key === key ? list.refs : [];
  return <div className="refbar"><div className="dropdown"><button className="btn" onClick={() => setOpen((value) => !value)} title={refname}><span className="muted">{refKind}:</span> <strong>{refKind === "commit" ? refname.slice(0, 7) : refname.length > 28 ? refname.slice(0, 25) + "…" : refname}</strong> <span className="caret">▾</span></button>{open && <div className="menu"><input autoFocus placeholder={`Find a ${tab === "tags" ? "tag" : "branch"}…`} value={query} onChange={(event) => setQuery(event.target.value)} /><div className="menu-tabs"><button className={tab === "branches" ? "active" : ""} onClick={() => setTab("branches")}>Branches</button><button className={tab === "tags" ? "active" : ""} onClick={() => setTab("tags")}>Tags</button></div><ul>{shown.map((ref) => <li key={ref.name} className={ref.name === refname ? "current" : ""}><button type="button" className="ref-option" onClick={() => go(ref.name)} aria-current={ref.name === refname ? "true" : undefined}>{ref.name}{tab === "branches" && ref.name === refs.head?.name && <span className="pill default">default</span>}</button></li>)}{list.key === key && list.error && <li className="flash error small" role="alert">Could not load {tab}: {list.error}</li>}{shown.length === 0 && !list.loading && !list.error && <li className="muted">No matches</li>}{list.loading && shown.length === 0 && <li className="muted">Loading…</li>}{list.more && <li className="muted small">Showing first {shown.length}; type to narrow</li>}</ul></div>}</div><div className="crumbs"><Link to={`/${full}/${crumbKind}/${refname}`} className="strong">{full.split("/")[1]}</Link>{segments.map((segment, index) => { const sub = segments.slice(0, index + 1).join("/"); const last = index === segments.length - 1; return <span key={sub}><span className="muted"> / </span>{last ? <strong>{segment}</strong> : <Link to={`/${full}/${crumbKind}/${refname}/${sub}`}>{segment}</Link>}</span>; })}</div><span className="spacer" />{page === "tree" && <Link className="btn" to={`/${full}/commits/${refname}${path ? "/" + path : ""}`}>History</Link>}</div>;
}
